name: CICD

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build with shadow-cljs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create the nodejs app
        run: |
          cd ./projects/main/
          npm install
          npx shadow-cljs release server
  deploy:
    name: Deploy to Cloudflare
    runs-on: ubuntu-latest
    needs: [build]
    defaults:
      run:
        shell: bash
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Apply
        run: |
            ls -l
            cd ./projects/main/terraform
            export TF_VAR_cloudflare_api_token=${{ secrets.CLOUDFLARE_API_TOKEN }}
            terraform init
            terraform apply -auto-approve